import React, { Component } from 'react';
import { Link } from 'react-router-dom';

class About extends Component {
  render() {
    return <div>
      <h4>About</h4>
      <p>This is About page.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nec feugiat in fermentum posuere urna. Id velit ut tortor pretium viverra suspendisse. Vestibulum morbi blandit cursus risus. Urna porttitor rhoncus dolor purus non. Risus in hendrerit gravida rutrum quisque non. Penatibus et magnis dis parturient. Purus gravida quis blandit turpis cursus in hac. Orci nulla pellentesque dignissim enim sit amet. Orci nulla pellentesque dignissim enim sit amet venenatis urna. Facilisi morbi tempus iaculis urna.</p>
      <p>Ridiculus mus mauris vitae ultricies leo integer malesuada nunc vel. Facilisis magna etiam tempor orci eu. Leo vel orci porta non pulvinar neque laoreet suspendisse interdum. Duis ut diam quam nulla porttitor massa id neque aliquam. In ante metus dictum at. Suspendisse in est ante in nibh mauris cursus mattis. Velit laoreet id donec ultrices tincidunt arcu non sodales. Felis eget velit aliquet sagittis id consectetur purus ut. Penatibus et magnis dis parturient montes. Aliquam vestibulum morbi blandit cursus.</p>
      <p>Quam id leo in vitae. Tempus urna et pharetra pharetra massa. Faucibus a pellentesque sit amet. Tincidunt ornare massa eget egestas purus viverra accumsan in. Iaculis urna id volutpat lacus laoreet non curabitur. Urna neque viverra justo nec ultrices. Proin libero nunc consequat interdum. Donec pretium vulputate sapien nec. Pellentesque habitant morbi tristique senectus. Convallis a cras semper auctor neque vitae. Sollicitudin ac orci phasellus egestas tellus rutrum. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Sit amet mauris commodo quis imperdiet massa. A condimentum vitae sapien pellentesque. Vel eros donec ac odio tempor orci dapibus ultrices. Nibh mauris cursus mattis molestie a iaculis at erat.</p>
      <p>Ultricies tristique nulla aliquet enim tortor at auctor. Eu non diam phasellus vestibulum. Nullam non nisi est sit amet facilisis magna. Id faucibus nisl tincidunt eget nullam non. Tincidunt ornare massa eget egestas purus viverra accumsan in. Porta nibh venenatis cras sed felis eget. Luctus venenatis lectus magna fringilla. Duis at tellus at urna condimentum mattis pellentesque id. Pellentesque habitant morbi tristique senectus et netus et malesuada fames. Habitasse platea dictumst quisque sagittis purus sit. Sed risus ultricies tristique nulla aliquet enim tortor at auctor. Quis vel eros donec ac. Nibh mauris cursus mattis molestie a. Ipsum dolor sit amet consectetur adipiscing. Cras ornare arcu dui vivamus arcu. Sed faucibus turpis in eu mi bibendum. In est ante in nibh mauris cursus mattis molestie a. Condimentum vitae sapien pellentesque habitant morbi. In egestas erat imperdiet sed.</p>
      <p>Enim ut sem viverra aliquet eget sit amet tellus. Ac tincidunt vitae semper quis lectus nulla at volutpat diam. Nunc mi ipsum faucibus vitae aliquet nec. Purus gravida quis blandit turpis cursus in hac habitasse. Purus in mollis nunc sed id semper. Est sit amet facilisis magna etiam tempor orci eu lobortis. Et tortor consequat id porta nibh venenatis cras. Ac tincidunt vitae semper quis lectus nulla at. Risus pretium quam vulputate dignissim. Sit amet aliquam id diam maecenas ultricies mi eget mauris. Tincidunt ornare massa eget egestas. Tellus cras adipiscing enim eu. In arcu cursus euismod quis viverra nibh cras pulvinar. Interdum posuere lorem ipsum dolor sit amet consectetur. Auctor urna nunc id cursus. Id interdum velit laoreet id donec ultrices. Tortor dignissim convallis aenean et tortor at.</p>
      <p>Tincidunt lobortis feugiat vivamus at augue eget arcu dictum varius. Nam libero justo laoreet sit amet cursus. Quis enim lobortis scelerisque fermentum dui. Elit eget gravida cum sociis natoque penatibus et magnis. Rutrum quisque non tellus orci ac auctor augue mauris. Lacinia at quis risus sed vulputate odio ut enim. Arcu felis bibendum ut tristique et egestas. Nisl purus in mollis nunc. Cursus sit amet dictum sit amet justo donec. Integer eget aliquet nibh praesent tristique magna sit amet. Velit dignissim sodales ut eu sem integer vitae justo. At in tellus integer feugiat scelerisque varius. Fames ac turpis egestas sed tempus urna et. Nibh sit amet commodo nulla facilisi nullam vehicula ipsum a. Viverra justo nec ultrices dui sapien eget mi.</p>
      <p>Urna id volutpat lacus laoreet non curabitur gravida arcu. Pulvinar mattis nunc sed blandit libero. Convallis convallis tellus id interdum velit laoreet id donec ultrices. Nisl suscipit adipiscing bibendum est ultricies integer. Volutpat consequat mauris nunc congue nisi vitae suscipit tellus. Velit ut tortor pretium viverra suspendisse potenti nullam ac tortor. Neque viverra justo nec ultrices dui sapien eget mi. Sodales ut eu sem integer vitae justo eget magna. Massa sed elementum tempus egestas sed sed risus pretium. Et egestas quis ipsum suspendisse ultrices gravida. Nullam non nisi est sit. Elit at imperdiet dui accumsan sit amet nulla facilisi. Ut etiam sit amet nisl purus in mollis nunc.</p>
      <p>Sodales neque sodales ut etiam. Magna fermentum iaculis eu non diam phasellus vestibulum. Lorem mollis aliquam ut porttitor. Etiam dignissim diam quis enim lobortis scelerisque fermentum dui faucibus. Sollicitudin ac orci phasellus egestas tellus rutrum. Id ornare arcu odio ut. Luctus accumsan tortor posuere ac ut consequat semper viverra. Et malesuada fames ac turpis egestas. Auctor eu augue ut lectus arcu bibendum at varius vel. Cras pulvinar mattis nunc sed blandit libero volutpat sed cras. Quis blandit turpis cursus in hac habitasse platea. Enim ut sem viverra aliquet eget sit. Vel eros donec ac odio tempor orci. Vitae et leo duis ut diam quam. Viverra mauris in aliquam sem fringilla ut morbi tincidunt. Nam at lectus urna duis convallis convallis tellus id. Mattis enim ut tellus elementum sagittis vitae et leo duis.</p>
      <p>Ullamcorper a lacus vestibulum sed arcu. Nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Eu facilisis sed odio morbi. Tempor id eu nisl nunc mi ipsum. A diam sollicitudin tempor id eu nisl nunc mi. Congue eu consequat ac felis donec et. Lobortis scelerisque fermentum dui faucibus in ornare quam viverra. Nunc sed id semper risus. Sed tempus urna et pharetra pharetra. Etiam tempor orci eu lobortis. Senectus et netus et malesuada fames ac. Nulla aliquet enim tortor at auctor urna nunc id cursus. Enim eu turpis egestas pretium. Magna eget est lorem ipsum dolor. Odio tempor orci dapibus ultrices. Quis ipsum suspendisse ultrices gravida dictum.</p>
      <p>Semper eget duis at tellus. Cras fermentum odio eu feugiat pretium nibh ipsum. Odio euismod lacinia at quis risus sed vulputate odio ut. Suscipit adipiscing bibendum est ultricies integer quis auctor elit sed. Laoreet sit amet cursus sit amet dictum sit amet justo. Lobortis elementum nibh tellus molestie nunc non blandit. Eros donec ac odio tempor orci dapibus ultrices in. Orci sagittis eu volutpat odio. Diam sollicitudin tempor id eu. Condimentum lacinia quis vel eros donec ac odio tempor orci. In massa tempor nec feugiat. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Cursus in hac habitasse platea dictumst quisque sagittis purus sit. Non arcu risus quis varius quam. Amet cursus sit amet dictum sit.</p>
      <p>Pharetra sit amet aliquam id diam maecenas. Sodales ut eu sem integer. Consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Massa eget egestas purus viverra accumsan in nisl nisi scelerisque. Bibendum neque egestas congue quisque egestas diam. Gravida dictum fusce ut placerat orci nulla pellentesque. Tortor condimentum lacinia quis vel. Sit amet volutpat consequat mauris nunc congue nisi vitae suscipit. Vestibulum lorem sed risus ultricies tristique nulla aliquet enim tortor. Volutpat diam ut venenatis tellus in metus. Imperdiet nulla malesuada pellentesque elit. Consectetur libero id faucibus nisl tincidunt eget. Arcu dui vivamus arcu felis bibendum ut tristique et egestas. Ullamcorper a lacus vestibulum sed arcu non. Commodo sed egestas egestas fringilla. Commodo elit at imperdiet dui accumsan sit amet nulla facilisi. Cursus eget nunc scelerisque viverra mauris in aliquam sem. Nunc id cursus metus aliquam eleifend mi. Ultrices sagittis orci a scelerisque purus semper eget duis.</p>
      <p>Commodo odio aenean sed adipiscing diam donec adipiscing tristique risus. Massa tempor nec feugiat nisl pretium fusce. Felis eget nunc lobortis mattis aliquam faucibus. Volutpat consequat mauris nunc congue nisi vitae suscipit tellus mauris. Non arcu risus quis varius quam. Egestas congue quisque egestas diam in arcu. Sit amet justo donec enim diam vulputate ut. Fermentum dui faucibus in ornare. Nibh tortor id aliquet lectus proin. Vulputate eu scelerisque felis imperdiet. Sodales neque sodales ut etiam sit amet nisl purus. Dictumst quisque sagittis purus sit amet. Purus in massa tempor nec feugiat nisl pretium.</p>
      <p>At consectetur lorem donec massa sapien faucibus et. Risus at ultrices mi tempus. Neque viverra justo nec ultrices dui sapien eget mi proin. Eget magna fermentum iaculis eu non diam phasellus vestibulum lorem. Eu ultrices vitae auctor eu. Non nisi est sit amet facilisis. Quis auctor elit sed vulputate mi sit. Diam phasellus vestibulum lorem sed risus ultricies tristique. Fusce ut placerat orci nulla pellentesque dignissim. Cursus eget nunc scelerisque viverra mauris in. Congue mauris rhoncus aenean vel elit. Aliquam purus sit amet luctus.</p>
      <p>Vitae semper quis lectus nulla at volutpat. Varius quam quisque id diam vel. Aenean sed adipiscing diam donec adipiscing. Massa vitae tortor condimentum lacinia quis vel eros donec ac. Est ante in nibh mauris cursus mattis. Euismod nisi porta lorem mollis aliquam ut porttitor leo. Feugiat pretium nibh ipsum consequat nisl vel pretium lectus. Odio ut sem nulla pharetra diam sit amet. Massa ultricies mi quis hendrerit dolor magna eget. Fringilla est ullamcorper eget nulla. Elementum facilisis leo vel fringilla est. Erat velit scelerisque in dictum non consectetur.</p>
      <p>Blandit massa enim nec dui nunc mattis. Felis bibendum ut tristique et. Aliquam id diam maecenas ultricies mi eget. Etiam sit amet nisl purus in mollis nunc sed. Libero volutpat sed cras ornare arcu dui vivamus arcu. Feugiat nisl pretium fusce id velit ut tortor pretium viverra. Integer feugiat scelerisque varius morbi. Donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum arcu. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet commodo. In hendrerit gravida rutrum quisque non tellus. Amet facilisis magna etiam tempor orci eu lobortis. In ornare quam viverra orci sagittis eu volutpat odio facilisis. Accumsan lacus vel facilisis volutpat est velit egestas dui. Fringilla urna porttitor rhoncus dolor purus non enim. Elementum nibh tellus molestie nunc non blandit massa. Diam quis enim lobortis scelerisque fermentum dui.</p>
      <Link to="/contact">Contact - Ignore "/contact" route for scroll to the top</Link>
    </div>
  }
}

export default About;