import React, { Component } from 'react';
import { Link } from 'react-router-dom';

class Contact extends Component {
  render() {
    return <div>
      <h4>Contact</h4>
      <p>This is Contact page.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elementum facilisis leo vel fringilla. Vitae ultricies leo integer malesuada. Purus faucibus ornare suspendisse sed nisi lacus sed. Bibendum neque egestas congue quisque egestas diam in. Morbi non arcu risus quis. Sed odio morbi quis commodo odio aenean sed adipiscing diam. Viverra maecenas accumsan lacus vel facilisis. Ornare massa eget egestas purus. Eu lobortis elementum nibh tellus. Elementum integer enim neque volutpat ac. Mauris augue neque gravida in. Et ligula ullamcorper malesuada proin libero nunc. Fusce ut placerat orci nulla pellentesque dignissim. Viverra aliquet eget sit amet tellus cras. Orci a scelerisque purus semper eget duis at tellus at. Dui accumsan sit amet nulla facilisi morbi tempus iaculis. Sed vulputate mi sit amet mauris. Viverra ipsum nunc aliquet bibendum enim facilisis gravida.</p>
      <p>Nulla facilisi cras fermentum odio eu feugiat. Justo nec ultrices dui sapien eget mi proin sed. Egestas maecenas pharetra convallis posuere. Adipiscing diam donec adipiscing tristique risus nec feugiat in. Sed blandit libero volutpat sed cras ornare arcu dui. Commodo viverra maecenas accumsan lacus vel. Ut lectus arcu bibendum at varius vel. Ante in nibh mauris cursus. Porta lorem mollis aliquam ut porttitor. Amet porttitor eget dolor morbi non arcu. Viverra nibh cras pulvinar mattis nunc sed blandit libero volutpat. Tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus. Sapien pellentesque habitant morbi tristique senectus et netus. Lectus mauris ultrices eros in cursus turpis massa. Egestas maecenas pharetra convallis posuere morbi leo urna molestie at. Purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus.</p>
      <p>Faucibus et molestie ac feugiat sed. Fringilla est ullamcorper eget nulla facilisi etiam. Velit egestas dui id ornare arcu odio. Mi quis hendrerit dolor magna eget est lorem ipsum dolor. Tortor aliquam nulla facilisi cras fermentum odio eu. Elementum nibh tellus molestie nunc. Neque gravida in fermentum et sollicitudin ac orci phasellus. Sit amet cursus sit amet dictum sit amet justo donec. Sit amet nisl suscipit adipiscing bibendum est ultricies integer. Faucibus turpis in eu mi bibendum neque egestas congue. Lectus urna duis convallis convallis tellus id. Bibendum arcu vitae elementum curabitur vitae. Amet cursus sit amet dictum sit amet justo donec enim. Aliquet risus feugiat in ante metus dictum at tempor. Quam pellentesque nec nam aliquam sem et tortor. Amet purus gravida quis blandit turpis cursus in. Diam phasellus vestibulum lorem sed risus ultricies. Tristique senectus et netus et malesuada.</p>
      <p>In egestas erat imperdiet sed euismod nisi porta. Enim diam vulputate ut pharetra. Dignissim enim sit amet venenatis urna cursus. Cursus turpis massa tincidunt dui ut ornare. Id venenatis a condimentum vitae sapien pellentesque habitant. Ipsum dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Feugiat nisl pretium fusce id velit ut tortor pretium viverra. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget arcu. Mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Aliquet risus feugiat in ante metus dictum at tempor commodo. Nibh tellus molestie nunc non blandit massa enim nec dui. Etiam erat velit scelerisque in.</p>
      <p>Ornare massa eget egestas purus viverra accumsan in. Vitae semper quis lectus nulla. Varius morbi enim nunc faucibus a. Vulputate mi sit amet mauris. Euismod quis viverra nibh cras pulvinar mattis nunc sed blandit. Nisi lacus sed viverra tellus in hac habitasse. Sollicitudin tempor id eu nisl nunc. Eu feugiat pretium nibh ipsum consequat nisl. Consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Ipsum a arcu cursus vitae congue mauris rhoncus aenean. Et netus et malesuada fames ac turpis egestas. Habitant morbi tristique senectus et netus et malesuada. Morbi tristique senectus et netus et malesuada fames. Dignissim diam quis enim lobortis scelerisque fermentum. Duis at tellus at urna condimentum. Imperdiet massa tincidunt nunc pulvinar sapien et.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elementum facilisis leo vel fringilla. Vitae ultricies leo integer malesuada. Purus faucibus ornare suspendisse sed nisi lacus sed. Bibendum neque egestas congue quisque egestas diam in. Morbi non arcu risus quis. Sed odio morbi quis commodo odio aenean sed adipiscing diam. Viverra maecenas accumsan lacus vel facilisis. Ornare massa eget egestas purus. Eu lobortis elementum nibh tellus. Elementum integer enim neque volutpat ac. Mauris augue neque gravida in. Et ligula ullamcorper malesuada proin libero nunc. Fusce ut placerat orci nulla pellentesque dignissim. Viverra aliquet eget sit amet tellus cras. Orci a scelerisque purus semper eget duis at tellus at. Dui accumsan sit amet nulla facilisi morbi tempus iaculis. Sed vulputate mi sit amet mauris. Viverra ipsum nunc aliquet bibendum enim facilisis gravida.</p>
      <p>Nulla facilisi cras fermentum odio eu feugiat. Justo nec ultrices dui sapien eget mi proin sed. Egestas maecenas pharetra convallis posuere. Adipiscing diam donec adipiscing tristique risus nec feugiat in. Sed blandit libero volutpat sed cras ornare arcu dui. Commodo viverra maecenas accumsan lacus vel. Ut lectus arcu bibendum at varius vel. Ante in nibh mauris cursus. Porta lorem mollis aliquam ut porttitor. Amet porttitor eget dolor morbi non arcu. Viverra nibh cras pulvinar mattis nunc sed blandit libero volutpat. Tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus. Sapien pellentesque habitant morbi tristique senectus et netus. Lectus mauris ultrices eros in cursus turpis massa. Egestas maecenas pharetra convallis posuere morbi leo urna molestie at. Purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus.</p>
      <p>Faucibus et molestie ac feugiat sed. Fringilla est ullamcorper eget nulla facilisi etiam. Velit egestas dui id ornare arcu odio. Mi quis hendrerit dolor magna eget est lorem ipsum dolor. Tortor aliquam nulla facilisi cras fermentum odio eu. Elementum nibh tellus molestie nunc. Neque gravida in fermentum et sollicitudin ac orci phasellus. Sit amet cursus sit amet dictum sit amet justo donec. Sit amet nisl suscipit adipiscing bibendum est ultricies integer. Faucibus turpis in eu mi bibendum neque egestas congue. Lectus urna duis convallis convallis tellus id. Bibendum arcu vitae elementum curabitur vitae. Amet cursus sit amet dictum sit amet justo donec enim. Aliquet risus feugiat in ante metus dictum at tempor. Quam pellentesque nec nam aliquam sem et tortor. Amet purus gravida quis blandit turpis cursus in. Diam phasellus vestibulum lorem sed risus ultricies. Tristique senectus et netus et malesuada.</p>
      <p>In egestas erat imperdiet sed euismod nisi porta. Enim diam vulputate ut pharetra. Dignissim enim sit amet venenatis urna cursus. Cursus turpis massa tincidunt dui ut ornare. Id venenatis a condimentum vitae sapien pellentesque habitant. Ipsum dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Feugiat nisl pretium fusce id velit ut tortor pretium viverra. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget arcu. Mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Aliquet risus feugiat in ante metus dictum at tempor commodo. Nibh tellus molestie nunc non blandit massa enim nec dui. Etiam erat velit scelerisque in.</p>
      <p>Ornare massa eget egestas purus viverra accumsan in. Vitae semper quis lectus nulla. Varius morbi enim nunc faucibus a. Vulputate mi sit amet mauris. Euismod quis viverra nibh cras pulvinar mattis nunc sed blandit. Nisi lacus sed viverra tellus in hac habitasse. Sollicitudin tempor id eu nisl nunc. Eu feugiat pretium nibh ipsum consequat nisl. Consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Ipsum a arcu cursus vitae congue mauris rhoncus aenean. Et netus et malesuada fames ac turpis egestas. Habitant morbi tristique senectus et netus et malesuada. Morbi tristique senectus et netus et malesuada fames. Dignissim diam quis enim lobortis scelerisque fermentum. Duis at tellus at urna condimentum. Imperdiet massa tincidunt nunc pulvinar sapien et.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elementum facilisis leo vel fringilla. Vitae ultricies leo integer malesuada. Purus faucibus ornare suspendisse sed nisi lacus sed. Bibendum neque egestas congue quisque egestas diam in. Morbi non arcu risus quis. Sed odio morbi quis commodo odio aenean sed adipiscing diam. Viverra maecenas accumsan lacus vel facilisis. Ornare massa eget egestas purus. Eu lobortis elementum nibh tellus. Elementum integer enim neque volutpat ac. Mauris augue neque gravida in. Et ligula ullamcorper malesuada proin libero nunc. Fusce ut placerat orci nulla pellentesque dignissim. Viverra aliquet eget sit amet tellus cras. Orci a scelerisque purus semper eget duis at tellus at. Dui accumsan sit amet nulla facilisi morbi tempus iaculis. Sed vulputate mi sit amet mauris. Viverra ipsum nunc aliquet bibendum enim facilisis gravida.</p>
      <p>Nulla facilisi cras fermentum odio eu feugiat. Justo nec ultrices dui sapien eget mi proin sed. Egestas maecenas pharetra convallis posuere. Adipiscing diam donec adipiscing tristique risus nec feugiat in. Sed blandit libero volutpat sed cras ornare arcu dui. Commodo viverra maecenas accumsan lacus vel. Ut lectus arcu bibendum at varius vel. Ante in nibh mauris cursus. Porta lorem mollis aliquam ut porttitor. Amet porttitor eget dolor morbi non arcu. Viverra nibh cras pulvinar mattis nunc sed blandit libero volutpat. Tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus. Sapien pellentesque habitant morbi tristique senectus et netus. Lectus mauris ultrices eros in cursus turpis massa. Egestas maecenas pharetra convallis posuere morbi leo urna molestie at. Purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus.</p>
      <p>Faucibus et molestie ac feugiat sed. Fringilla est ullamcorper eget nulla facilisi etiam. Velit egestas dui id ornare arcu odio. Mi quis hendrerit dolor magna eget est lorem ipsum dolor. Tortor aliquam nulla facilisi cras fermentum odio eu. Elementum nibh tellus molestie nunc. Neque gravida in fermentum et sollicitudin ac orci phasellus. Sit amet cursus sit amet dictum sit amet justo donec. Sit amet nisl suscipit adipiscing bibendum est ultricies integer. Faucibus turpis in eu mi bibendum neque egestas congue. Lectus urna duis convallis convallis tellus id. Bibendum arcu vitae elementum curabitur vitae. Amet cursus sit amet dictum sit amet justo donec enim. Aliquet risus feugiat in ante metus dictum at tempor. Quam pellentesque nec nam aliquam sem et tortor. Amet purus gravida quis blandit turpis cursus in. Diam phasellus vestibulum lorem sed risus ultricies. Tristique senectus et netus et malesuada.</p>
      <p>In egestas erat imperdiet sed euismod nisi porta. Enim diam vulputate ut pharetra. Dignissim enim sit amet venenatis urna cursus. Cursus turpis massa tincidunt dui ut ornare. Id venenatis a condimentum vitae sapien pellentesque habitant. Ipsum dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Feugiat nisl pretium fusce id velit ut tortor pretium viverra. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget arcu. Mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Aliquet risus feugiat in ante metus dictum at tempor commodo. Nibh tellus molestie nunc non blandit massa enim nec dui. Etiam erat velit scelerisque in.</p>
      <p>Ornare massa eget egestas purus viverra accumsan in. Vitae semper quis lectus nulla. Varius morbi enim nunc faucibus a. Vulputate mi sit amet mauris. Euismod quis viverra nibh cras pulvinar mattis nunc sed blandit. Nisi lacus sed viverra tellus in hac habitasse. Sollicitudin tempor id eu nisl nunc. Eu feugiat pretium nibh ipsum consequat nisl. Consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Ipsum a arcu cursus vitae congue mauris rhoncus aenean. Et netus et malesuada fames ac turpis egestas. Habitant morbi tristique senectus et netus et malesuada. Morbi tristique senectus et netus et malesuada fames. Dignissim diam quis enim lobortis scelerisque fermentum. Duis at tellus at urna condimentum. Imperdiet massa tincidunt nunc pulvinar sapien et.</p>
    </div>
  }
}

export default Contact;